/** Declaration file generated by dts-gen */

export = awesome_typescript_loader;

declare function awesome_typescript_loader(text: any): void;

declare namespace awesome_typescript_loader {
    class CheckerPlugin {
        constructor();

        apply(compiler: any): void;

    }

    class TsConfigPathsPlugin {
        constructor(config: any);

        apply(resolver: any): void;

        createPlugin(resolver: any, mapping: any, ...args: any[]): any;

        isTyping(target: any): any;

    }

    const prototype: {
    };

}

