/** Declaration file generated by dts-gen */

declare module 'good' {

  export function register(server: any, options: any, next: any): any;

  export namespace register {
      const attributes: {
          pkg: {
              dependencies: {
                  hoek: string;
                  joi: string;
                  oppsy: string;
                  pumpify: string;
              };
              description: string;
              devDependencies: {
                  async: string;
                  code: string;
                  hapi: string;
                  lab: string;
                  wreck: string;
              };
              engines: {
                  node: string;
              };
              keywords: string[];
              license: string;
              main: string;
              name: string;
              peerDependencies: {
                  hapi: string;
              };
              repository: string;
              scripts: {
                  test: string;
              };
              version: string;
          };
      };

  }
}
